name: Run tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        # Final value should correspond to rust-version in Cargo.toml
        toolchain: [stable, nightly, "1.82"]
        platform: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          toolchain:  ${{ matrix.toolchain }}
      - name: Display versions
        run: |
          cargo -V
          rustc -V
      - name: Run tests
        run: cargo test
      - name: Run tests with bigint feature
        run: cargo test --features bigint

  semver:
    name: Check Semantic Versioning
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: obi1kenobi/cargo-semver-checks-action@6b69fcf40e9b5fb17adeb57e4b6ecd020649a239 # v2.9
        with:
          package: vhpi, vhpi-sys, vhpi-shim

  msrv:
    name: Check Minimum Rust Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: taiki-e/cache-cargo-install-action@417450f3c33ee20393705369577571770643d4c7 # v3.0.7
        with:
          tool: cargo-msrv
      - name: Check MSRV for vhpi
        working-directory: vhpi
        run: cargo msrv verify
      - name: Check MSRV for vhpi-sys
        working-directory: vhpi-sys
        run: cargo msrv verify
      - name: Check MSRV for vhpi-shim
        working-directory: vhpi-shim
        run: cargo msrv verify
